/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tpmaquianasql.View.Consultas;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.DateTimeException;
import java.time.LocalDate;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.mycompany.tpmaquianasql.Controler.Conexion;
import com.mycompany.tpmaquianasql.util.Tabla;

/**
 *
 * @author ivanb
 */
public class DateInputPane extends javax.swing.JPanel {

    private Color defaultFontColor = new Color(190, 190, 190);
    private Color deleteButtonFontColor = new Color(187, 187, 186);
    private Color deleteButtonFontColorOnHover = new Color(255, 255, 255);

    private Conexion conexion;

    /**
     * Creates new form DateInputPane
     */
    public DateInputPane(Conexion conexion) {
        initComponents();

        this.conexion = conexion;
    }

    private void changePane(JPanel jPanel) {
        Contenedor.setLayout(new java.awt.CardLayout());
        Contenedor.removeAll();
        Contenedor.add(jPanel);
        Contenedor.revalidate();
        Contenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        errMsg1 = new javax.swing.JLabel();
        dia1Field = new javax.swing.JTextField();
        fecha1Label = new javax.swing.JLabel();
        mes1Field = new javax.swing.JTextField();
        anio1Field = new javax.swing.JTextField();
        errMsg2 = new javax.swing.JLabel();
        dia2Field = new javax.swing.JTextField();
        fecha2Label = new javax.swing.JLabel();
        mes2Field = new javax.swing.JTextField();
        anio2Field = new javax.swing.JTextField();
        queryButtonP = new javax.swing.JPanel();
        queryButtonL = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errMsg1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errMsg1.setForeground(new java.awt.Color(255, 0, 0));
        errMsg1.setText("Mensaje de error");
        Contenedor.add(errMsg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 190, -1));

        dia1Field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dia1Field.setForeground(new java.awt.Color(190, 190, 190));
        dia1Field.setText("Día");
        dia1Field.setBorder(null);
        dia1Field.setPreferredSize(new java.awt.Dimension(170, 19));
        dia1Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dia1FieldFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                dia1FieldFocusLost(evt);
            }
        });
        dia1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dia1FieldActionPerformed(evt);
            }
        });
        Contenedor.add(dia1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, -1));

        fecha1Label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fecha1Label.setForeground(new java.awt.Color(0, 0, 0));
        fecha1Label.setText("Fecha de inicio");
        Contenedor.add(fecha1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        mes1Field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mes1Field.setForeground(new java.awt.Color(190, 190, 190));
        mes1Field.setText("Mes");
        mes1Field.setBorder(null);
        mes1Field.setPreferredSize(new java.awt.Dimension(170, 19));
        mes1Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mes1FieldFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                mes1FieldFocusLost(evt);
            }
        });
        mes1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes1FieldActionPerformed(evt);
            }
        });
        Contenedor.add(mes1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 40, 20));

        anio1Field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        anio1Field.setForeground(new java.awt.Color(190, 190, 190));
        anio1Field.setText("Año");
        anio1Field.setBorder(null);
        anio1Field.setPreferredSize(new java.awt.Dimension(170, 19));
        anio1Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                anio1FieldFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                anio1FieldFocusLost(evt);
            }
        });
        anio1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anio1FieldActionPerformed(evt);
            }
        });
        Contenedor.add(anio1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 60, 20));

        errMsg2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        errMsg2.setForeground(new java.awt.Color(255, 0, 0));
        errMsg2.setText("Mensaje de error");
        Contenedor.add(errMsg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 190, -1));

        dia2Field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dia2Field.setForeground(new java.awt.Color(190, 190, 190));
        dia2Field.setText("Día");
        dia2Field.setBorder(null);
        dia2Field.setPreferredSize(new java.awt.Dimension(170, 19));
        dia2Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dia2FieldFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                dia2FieldFocusLost(evt);
            }
        });
        dia2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dia2FieldActionPerformed(evt);
            }
        });
        Contenedor.add(dia2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 40, -1));

        fecha2Label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fecha2Label.setForeground(new java.awt.Color(0, 0, 0));
        fecha2Label.setText("Fecha de fin");
        Contenedor.add(fecha2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        mes2Field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mes2Field.setForeground(new java.awt.Color(190, 190, 190));
        mes2Field.setText("Mes");
        mes2Field.setBorder(null);
        mes2Field.setPreferredSize(new java.awt.Dimension(170, 19));
        mes2Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mes2FieldFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                mes2FieldFocusLost(evt);
            }
        });
        mes2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes2FieldActionPerformed(evt);
            }
        });
        Contenedor.add(mes2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 40, 20));

        anio2Field.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        anio2Field.setForeground(new java.awt.Color(190, 190, 190));
        anio2Field.setText("Año");
        anio2Field.setBorder(null);
        anio2Field.setPreferredSize(new java.awt.Dimension(170, 19));
        anio2Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                anio2FieldFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                anio2FieldFocusLost(evt);
            }
        });
        anio2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anio2FieldActionPerformed(evt);
            }
        });
        Contenedor.add(anio2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 60, 20));

        queryButtonP.setBackground(new java.awt.Color(18, 33, 69));
        queryButtonP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        queryButtonP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        queryButtonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                queryButtonPMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                queryButtonPMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                queryButtonPMouseExited(evt);
            }
        });

        queryButtonL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        queryButtonL.setForeground(new java.awt.Color(187, 187, 186));
        queryButtonL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        queryButtonL.setText("Consultar");

        javax.swing.GroupLayout queryButtonPLayout = new javax.swing.GroupLayout(queryButtonP);
        queryButtonP.setLayout(queryButtonPLayout);
        queryButtonPLayout.setHorizontalGroup(
                queryButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, queryButtonPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(queryButtonL, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addContainerGap()));
        queryButtonPLayout.setVerticalGroup(
                queryButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, queryButtonPLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(queryButtonL)
                                .addContainerGap()));

        Contenedor.add(queryButtonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, -1));

        add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void dia1FieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_dia1FieldFocusGained
        if (dia1Field.getText().equals("Día")) {
            dia1Field.setText("");
        } else {
            dia1Field.selectAll();
        }
        dia1Field.setForeground(Color.BLACK);
    }// GEN-LAST:event_dia1FieldFocusGained

    private void dia1FieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_dia1FieldFocusLost
        if (dia1Field.getText().equals("")) {
            dia1Field.setText("Día");
            dia1Field.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_dia1FieldFocusLost

    private void dia1FieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dia1FieldActionPerformed
        mes1Field.requestFocus();
    }// GEN-LAST:event_dia1FieldActionPerformed

    private void queryButtonPMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_queryButtonPMouseClicked
        consultar();
    }// GEN-LAST:event_queryButtonPMouseClicked

    private void queryButtonPMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_queryButtonPMouseEntered
        queryButtonL.setForeground(deleteButtonFontColorOnHover);
    }// GEN-LAST:event_queryButtonPMouseEntered

    private void queryButtonPMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_queryButtonPMouseExited
        queryButtonL.setForeground(deleteButtonFontColor);
    }// GEN-LAST:event_queryButtonPMouseExited

    private void mes1FieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_mes1FieldFocusGained
        if (mes1Field.getText().equals("Mes")) {
            mes1Field.setText("");
        } else {
            mes1Field.selectAll();
        }
        mes1Field.setForeground(Color.BLACK);
    }// GEN-LAST:event_mes1FieldFocusGained

    private void mes1FieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_mes1FieldFocusLost
        if (mes1Field.getText().equals("")) {
            mes1Field.setText("Mes");
            mes1Field.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_mes1FieldFocusLost

    private void mes1FieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mes1FieldActionPerformed
        anio1Field.requestFocus();
    }// GEN-LAST:event_mes1FieldActionPerformed

    private void anio1FieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_anio1FieldFocusGained
        if (anio1Field.getText().equals("Año")) {
            anio1Field.setText("");
        } else {
            anio1Field.selectAll();
        }
        anio1Field.setForeground(Color.BLACK);
    }// GEN-LAST:event_anio1FieldFocusGained

    private void anio1FieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_anio1FieldFocusLost
        if (anio1Field.getText().equals("")) {
            anio1Field.setText("Año");
            anio1Field.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_anio1FieldFocusLost

    private void anio1FieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_anio1FieldActionPerformed
        dia2Field.requestFocus();
    }// GEN-LAST:event_anio1FieldActionPerformed

    private void dia2FieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_dia2FieldFocusGained
        if (dia2Field.getText().equals("Día")) {
            dia2Field.setText("");
        } else {
            dia2Field.selectAll();
        }
        dia2Field.setForeground(Color.BLACK);
    }// GEN-LAST:event_dia2FieldFocusGained

    private void dia2FieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_dia2FieldFocusLost
        if (dia2Field.getText().equals("")) {
            dia2Field.setText("Día");
            dia2Field.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_dia2FieldFocusLost

    private void dia2FieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dia2FieldActionPerformed
        mes2Field.requestFocus();
    }// GEN-LAST:event_dia2FieldActionPerformed

    private void mes2FieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_mes2FieldFocusGained
        if (mes2Field.getText().equals("Mes")) {
            mes2Field.setText("");
        } else {
            mes2Field.selectAll();
        }
        mes2Field.setForeground(Color.BLACK);
    }// GEN-LAST:event_mes2FieldFocusGained

    private void mes2FieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_mes2FieldFocusLost
        if (mes2Field.getText().equals("")) {
            mes2Field.setText("Mes");
            mes2Field.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_mes2FieldFocusLost

    private void mes2FieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mes2FieldActionPerformed
        anio2Field.requestFocus();
    }// GEN-LAST:event_mes2FieldActionPerformed

    private void anio2FieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_anio2FieldFocusGained
        if (anio2Field.getText().equals("Año")) {
            anio2Field.setText("");
        } else {
            anio2Field.selectAll();
        }
        anio2Field.setForeground(Color.BLACK);
    }// GEN-LAST:event_anio2FieldFocusGained

    private void anio2FieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_anio2FieldFocusLost
        if (anio2Field.getText().equals("")) {
            anio2Field.setText("Año");
            anio2Field.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_anio2FieldFocusLost

    private void anio2FieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_anio2FieldActionPerformed
        consultar();
    }// GEN-LAST:event_anio2FieldActionPerformed

    private void consultar() {
        queryButtonP.requestFocus();

        String diaTemp = dia1Field.getText(), mesTemp = mes1Field.getText(), anioTemp = anio1Field.getText();
        LocalDate fechaInicio = null, fechaFin = null;
        boolean correcto = true;

        if (diaTemp.equals("Día") || mesTemp.equals("Mes") || anioTemp.equals("Año")) {
            errMsg1.setText("Obligatorio");
            errMsg1.setVisible(true);
            correcto = false;
        } else {
            try {
                fechaInicio = LocalDate.of(Integer.parseInt(anioTemp), Integer.parseInt(mesTemp),
                        Integer.parseInt(diaTemp));
                errMsg1.setVisible(false);
            } catch (NumberFormatException e) {
                errMsg1.setText("Deben ser enteros");
                errMsg1.setVisible(true);
                correcto = false;
            } catch (DateTimeException e) {
                errMsg1.setText("Fecha inválida");
                errMsg1.setVisible(true);
                correcto = false;
            }
        }

        diaTemp = dia2Field.getText();
        mesTemp = mes2Field.getText();
        anioTemp = anio2Field.getText();

        if (diaTemp.equals("Día") || mesTemp.equals("Mes") || anioTemp.equals("Año") || anioTemp.equals("")) {
            errMsg2.setText("Obligatorio");
            errMsg2.setVisible(true);
            correcto = false;
        } else {
            try {
                fechaFin = LocalDate.of(Integer.parseInt(anioTemp), Integer.parseInt(mesTemp),
                        Integer.parseInt(diaTemp));
                errMsg2.setVisible(false);
            } catch (NumberFormatException e) {
                errMsg2.setText("Deben ser enteros");
                errMsg2.setVisible(true);
                correcto = false;
            } catch (DateTimeException e) {
                errMsg2.setText("Fecha inválida");
                errMsg2.setVisible(true);
                correcto = false;
            }
        }

        if (correcto) {
            try {
                Connection con = conexion.getConexion();
                PreparedStatement ps = con.prepareStatement("SELECT P.P_Cod Código, P_Nombre Nombre " +
                        "FROM Platos AS P, Consumos AS C, Se_Consume AS SC " +
                        "WHERE P.P_Cod=SC.P_Cod AND SC.C_Cod=C.C_Cod AND C_Fecha>=? AND C_Fecha<=?");

                ps.setDate(1, Date.valueOf(fechaInicio));
                ps.setDate(2, Date.valueOf(fechaFin));

                ResultSet rs = ps.executeQuery();

                changePane(new QueryTablePane(Tabla.resultToTable(rs),
                        "Platos consumidos entre " + fechaInicio + " y " + fechaFin));
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JTextField anio1Field;
    private javax.swing.JTextField anio2Field;
    private javax.swing.JTextField dia1Field;
    private javax.swing.JTextField dia2Field;
    private javax.swing.JLabel errMsg1;
    private javax.swing.JLabel errMsg2;
    private javax.swing.JLabel fecha1Label;
    private javax.swing.JLabel fecha2Label;
    private javax.swing.JTextField mes1Field;
    private javax.swing.JTextField mes2Field;
    private javax.swing.JLabel queryButtonL;
    private javax.swing.JPanel queryButtonP;
    // End of variables declaration//GEN-END:variables
}
