/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tpmaquianasql.View.Tablas;

import com.mycompany.tpmaquianasql.Controler.ConsumosData;
import com.mycompany.tpmaquianasql.Controler.MesasData;
import com.mycompany.tpmaquianasql.Controler.MozosData;
import com.mycompany.tpmaquianasql.Controler.PlatosData;
import com.mycompany.tpmaquianasql.Controler.Se_ConsumeData;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author ivanb
 */
public class TablePane extends javax.swing.JPanel {
    
    private ConsumosData consumosData;
    private MesasData mesasData;
    private MozosData mozosData;
    private PlatosData platosData;
    private Se_ConsumeData se_ConsumeData;

    private Color buttonFontColor = new Color(187, 187, 186);
    private Color buttonFontColorOnHover = new Color(255,255,255);
    /**
     * Creates new form TablePane
     */
    public TablePane(ConsumosData consumosData, MesasData mesasData, MozosData mozosData, PlatosData platosData,
            Se_ConsumeData se_ConsumeData) {
        initComponents();
        
        this.platosData = platosData;
        this.consumosData = consumosData;
        this.mesasData = mesasData;
        this.mozosData = mozosData;
        this.se_ConsumeData = se_ConsumeData;
    }
    
    private void changePane(JPanel jPanel) {
        Contenedor.setLayout(new java.awt.CardLayout());
        Contenedor.removeAll();
        Contenedor.add(jPanel);
        Contenedor.revalidate();
        Contenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraLateral = new javax.swing.JPanel();
        mozosTableButtonP = new javax.swing.JPanel();
        mozosTableButtonL = new javax.swing.JLabel();
        platosTableButtonP = new javax.swing.JPanel();
        platosTableButtonL = new javax.swing.JLabel();
        Contenedor = new javax.swing.JPanel();
        insertButtonL2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barraLateral.setBackground(new java.awt.Color(31, 115, 202));
        barraLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mozosTableButtonP.setBackground(new java.awt.Color(31, 115, 202));
        mozosTableButtonP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mozosTableButtonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mozosTableButtonPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mozosTableButtonPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mozosTableButtonPMouseExited(evt);
            }
        });

        mozosTableButtonL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mozosTableButtonL.setForeground(new java.awt.Color(187, 187, 186));
        mozosTableButtonL.setText("Mozos");

        javax.swing.GroupLayout mozosTableButtonPLayout = new javax.swing.GroupLayout(mozosTableButtonP);
        mozosTableButtonP.setLayout(mozosTableButtonPLayout);
        mozosTableButtonPLayout.setHorizontalGroup(
            mozosTableButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mozosTableButtonPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mozosTableButtonL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mozosTableButtonPLayout.setVerticalGroup(
            mozosTableButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mozosTableButtonPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mozosTableButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        barraLateral.add(mozosTableButtonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        platosTableButtonP.setBackground(new java.awt.Color(31, 115, 202));
        platosTableButtonP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        platosTableButtonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                platosTableButtonPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                platosTableButtonPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                platosTableButtonPMouseExited(evt);
            }
        });

        platosTableButtonL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        platosTableButtonL.setForeground(new java.awt.Color(187, 187, 186));
        platosTableButtonL.setText("Platos");

        javax.swing.GroupLayout platosTableButtonPLayout = new javax.swing.GroupLayout(platosTableButtonP);
        platosTableButtonP.setLayout(platosTableButtonPLayout);
        platosTableButtonPLayout.setHorizontalGroup(
            platosTableButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(platosTableButtonPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(platosTableButtonL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        platosTableButtonPLayout.setVerticalGroup(
            platosTableButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, platosTableButtonPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(platosTableButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        barraLateral.add(platosTableButtonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        add(barraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 510));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insertButtonL2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        insertButtonL2.setForeground(new java.awt.Color(51, 51, 51));
        insertButtonL2.setText("Seleccione la tabla que desea ver");
        Contenedor.add(insertButtonL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 650, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void mozosTableButtonPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mozosTableButtonPMouseClicked
        changePane(new GeneralTablePane(mozosData.getMozosTable()));
    }//GEN-LAST:event_mozosTableButtonPMouseClicked

    private void mozosTableButtonPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mozosTableButtonPMouseEntered
        mozosTableButtonL.setForeground(buttonFontColorOnHover);
    }//GEN-LAST:event_mozosTableButtonPMouseEntered

    private void mozosTableButtonPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mozosTableButtonPMouseExited
        mozosTableButtonL.setForeground(buttonFontColor);
    }//GEN-LAST:event_mozosTableButtonPMouseExited

    private void platosTableButtonPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_platosTableButtonPMouseClicked
        changePane(new GeneralTablePane(platosData.getPlatosTable()));
    }//GEN-LAST:event_platosTableButtonPMouseClicked

    private void platosTableButtonPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_platosTableButtonPMouseEntered
        platosTableButtonL.setForeground(buttonFontColorOnHover);
    }//GEN-LAST:event_platosTableButtonPMouseEntered

    private void platosTableButtonPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_platosTableButtonPMouseExited
        platosTableButtonL.setForeground(buttonFontColor);
    }//GEN-LAST:event_platosTableButtonPMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel barraLateral;
    private javax.swing.JLabel insertButtonL2;
    private javax.swing.JLabel mozosTableButtonL;
    private javax.swing.JPanel mozosTableButtonP;
    private javax.swing.JLabel platosTableButtonL;
    private javax.swing.JPanel platosTableButtonP;
    // End of variables declaration//GEN-END:variables
}
