/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package com.mycompany.tpmaquianasql.View;

/**
 *
 * @author ivanb
 */
public class DeleteJIFrame extends javax.swing.JInternalFrame {

    /** Creates new form DeleteJIFrame */
    public DeleteJIFrame() {
        initComponents();

        setErrMsgInVisible();
    }

    private void setErrMsgInVisible() {
        errMsg1.setVisible(false);

        errMsgMo1.setVisible(false);

        errMsgP1.setVisible(false);

        errMsgMe1.setVisible(false);

        errMsgSeC1.setVisible(false);
        errMsgSeC2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputTabbedPane = new javax.swing.JTabbedPane();
        InputConsumoPane = new javax.swing.JPanel();
        codigoCLabel = new javax.swing.JLabel();
        codigoTField = new javax.swing.JTextField();
        errMsg1 = new javax.swing.JLabel();
        InputMesaPane = new javax.swing.JPanel();
        codigoMeLabel = new javax.swing.JLabel();
        codigoMeTField = new javax.swing.JTextField();
        errMsgMe1 = new javax.swing.JLabel();
        InputMozoPane = new javax.swing.JPanel();
        codigoMLabel = new javax.swing.JLabel();
        codigoMTField = new javax.swing.JTextField();
        errMsgMo1 = new javax.swing.JLabel();
        InputPlatoPane = new javax.swing.JPanel();
        codigoPLabel = new javax.swing.JLabel();
        codigoPTField = new javax.swing.JTextField();
        errMsgP1 = new javax.swing.JLabel();
        InputSe_ConsumePane = new javax.swing.JPanel();
        codConsumoLabel = new javax.swing.JLabel();
        codPlatoLabel = new javax.swing.JLabel();
        codConsumoTField = new javax.swing.JTextField();
        codPlatoTfield = new javax.swing.JTextField();
        errMsgSeC1 = new javax.swing.JLabel();
        errMsgSeC2 = new javax.swing.JLabel();

        InputConsumoPane.setForeground(new java.awt.Color(255, 0, 0));

        codigoCLabel.setText("Código");

        errMsg1.setForeground(new java.awt.Color(255, 0, 0));
        errMsg1.setText("Mensaje de error");

        javax.swing.GroupLayout InputConsumoPaneLayout = new javax.swing.GroupLayout(InputConsumoPane);
        InputConsumoPane.setLayout(InputConsumoPaneLayout);
        InputConsumoPaneLayout.setHorizontalGroup(
                InputConsumoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputConsumoPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InputConsumoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(InputConsumoPaneLayout.createSequentialGroup()
                                                .addComponent(codigoCLabel)
                                                .addContainerGap(347, Short.MAX_VALUE))
                                        .addGroup(InputConsumoPaneLayout.createSequentialGroup()
                                                .addComponent(codigoTField, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(errMsg1)
                                                .addGap(0, 167, Short.MAX_VALUE)))));
        InputConsumoPaneLayout.setVerticalGroup(
                InputConsumoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputConsumoPaneLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(codigoCLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputConsumoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codigoTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsg1))
                                .addContainerGap(92, Short.MAX_VALUE)));

        InputTabbedPane.addTab("Consumo", InputConsumoPane);

        codigoMeLabel.setText("Código");

        errMsgMe1.setForeground(new java.awt.Color(255, 0, 0));
        errMsgMe1.setText("Mensaje de error");

        javax.swing.GroupLayout InputMesaPaneLayout = new javax.swing.GroupLayout(InputMesaPane);
        InputMesaPane.setLayout(InputMesaPaneLayout);
        InputMesaPaneLayout.setHorizontalGroup(
                InputMesaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputMesaPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InputMesaPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(codigoMeLabel)
                                        .addComponent(codigoMeTField, javax.swing.GroupLayout.PREFERRED_SIZE, 154,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(errMsgMe1)
                                .addContainerGap(129, Short.MAX_VALUE)));
        InputMesaPaneLayout.setVerticalGroup(
                InputMesaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputMesaPaneLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(codigoMeLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputMesaPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codigoMeTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgMe1))
                                .addContainerGap(92, Short.MAX_VALUE)));

        InputTabbedPane.addTab("Mesa", InputMesaPane);

        codigoMLabel.setText("Código");

        errMsgMo1.setForeground(new java.awt.Color(255, 0, 0));
        errMsgMo1.setText("Mensaje de error");

        javax.swing.GroupLayout InputMozoPaneLayout = new javax.swing.GroupLayout(InputMozoPane);
        InputMozoPane.setLayout(InputMozoPaneLayout);
        InputMozoPaneLayout.setHorizontalGroup(
                InputMozoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputMozoPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InputMozoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(codigoMLabel)
                                        .addComponent(codigoMTField, javax.swing.GroupLayout.PREFERRED_SIZE, 149,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(errMsgMo1)
                                .addContainerGap(134, Short.MAX_VALUE)));
        InputMozoPaneLayout.setVerticalGroup(
                InputMozoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputMozoPaneLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(codigoMLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputMozoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codigoMTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgMo1))
                                .addContainerGap(92, Short.MAX_VALUE)));

        InputTabbedPane.addTab("Mozo", InputMozoPane);

        codigoPLabel.setText("Código");

        errMsgP1.setForeground(new java.awt.Color(255, 0, 0));
        errMsgP1.setText("Mensaje de error");

        javax.swing.GroupLayout InputPlatoPaneLayout = new javax.swing.GroupLayout(InputPlatoPane);
        InputPlatoPane.setLayout(InputPlatoPaneLayout);
        InputPlatoPaneLayout.setHorizontalGroup(
                InputPlatoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputPlatoPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InputPlatoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(codigoPLabel)
                                        .addComponent(codigoPTField, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(errMsgP1)
                                .addContainerGap(133, Short.MAX_VALUE)));
        InputPlatoPaneLayout.setVerticalGroup(
                InputPlatoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputPlatoPaneLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(codigoPLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputPlatoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codigoPTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgP1))
                                .addContainerGap(92, Short.MAX_VALUE)));

        InputTabbedPane.addTab("Plato", InputPlatoPane);

        codConsumoLabel.setText("Código de consumo");

        codPlatoLabel.setText("Código de plato");

        errMsgSeC1.setForeground(new java.awt.Color(255, 0, 0));
        errMsgSeC1.setText("Mensaje de error");

        errMsgSeC2.setForeground(new java.awt.Color(255, 0, 0));
        errMsgSeC2.setText("Mensaje de error");

        javax.swing.GroupLayout InputSe_ConsumePaneLayout = new javax.swing.GroupLayout(InputSe_ConsumePane);
        InputSe_ConsumePane.setLayout(InputSe_ConsumePaneLayout);
        InputSe_ConsumePaneLayout.setHorizontalGroup(
                InputSe_ConsumePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputSe_ConsumePaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InputSe_ConsumePaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(codConsumoLabel)
                                        .addComponent(codPlatoLabel)
                                        .addComponent(codConsumoTField, javax.swing.GroupLayout.DEFAULT_SIZE, 150,
                                                Short.MAX_VALUE)
                                        .addComponent(codPlatoTfield))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InputSe_ConsumePaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(errMsgSeC2)
                                        .addComponent(errMsgSeC1))
                                .addContainerGap(133, Short.MAX_VALUE)));
        InputSe_ConsumePaneLayout.setVerticalGroup(
                InputSe_ConsumePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputSe_ConsumePaneLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(codConsumoLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputSe_ConsumePaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codConsumoTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgSeC1))
                                .addGap(20, 20, 20)
                                .addComponent(codPlatoLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputSe_ConsumePaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codPlatoTfield, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgSeC2))
                                .addContainerGap(22, Short.MAX_VALUE)));

        InputTabbedPane.addTab("Se Consume", InputSe_ConsumePane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(InputTabbedPane));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(InputTabbedPane)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InputConsumoPane;
    private javax.swing.JPanel InputMesaPane;
    private javax.swing.JPanel InputMozoPane;
    private javax.swing.JPanel InputPlatoPane;
    private javax.swing.JPanel InputSe_ConsumePane;
    private javax.swing.JTabbedPane InputTabbedPane;
    private javax.swing.JLabel codConsumoLabel;
    private javax.swing.JTextField codConsumoTField;
    private javax.swing.JLabel codPlatoLabel;
    private javax.swing.JTextField codPlatoTfield;
    private javax.swing.JLabel codigoCLabel;
    private javax.swing.JLabel codigoMLabel;
    private javax.swing.JTextField codigoMTField;
    private javax.swing.JLabel codigoMeLabel;
    private javax.swing.JTextField codigoMeTField;
    private javax.swing.JLabel codigoPLabel;
    private javax.swing.JTextField codigoPTField;
    private javax.swing.JTextField codigoTField;
    private javax.swing.JLabel errMsg1;
    private javax.swing.JLabel errMsgMe1;
    private javax.swing.JLabel errMsgMo1;
    private javax.swing.JLabel errMsgP1;
    private javax.swing.JLabel errMsgSeC1;
    private javax.swing.JLabel errMsgSeC2;
    // End of variables declaration//GEN-END:variables

}
