/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.tpmaquianasql.View;

import java.time.LocalTime;
import java.time.DateTimeException;
import java.time.LocalDate;

import com.mycompany.tpmaquianasql.Frame;
import com.mycompany.tpmaquianasql.Controler.ConsumosData;
import com.mycompany.tpmaquianasql.Controler.MesasData;
import com.mycompany.tpmaquianasql.Controler.MozosData;
import com.mycompany.tpmaquianasql.Controler.PlatosData;
import com.mycompany.tpmaquianasql.Controler.Se_ConsumeData;
import com.mycompany.tpmaquianasql.Model.Consumos;
import com.mycompany.tpmaquianasql.Model.Mesas;
import com.mycompany.tpmaquianasql.Model.Mozos;
import com.mycompany.tpmaquianasql.Model.Platos;
import com.mycompany.tpmaquianasql.Model.Se_Consume;

/**
 *
 * @author ivanb
 */
public class InputJIFrame extends javax.swing.JInternalFrame {

    private ConsumosData consumosData;
    private MesasData mesasData;
    private MozosData mozosData;
    private PlatosData platosData;
    private Se_ConsumeData se_ConsumeData;
    // Reference to the main JFrame to refresh
    private Frame parent;

    public InputJIFrame(ConsumosData consumosData, MesasData mesasData, MozosData mozosData, PlatosData platosData,
            Se_ConsumeData se_ConsumeData, Frame parent) {
        initComponents();

        this.platosData = platosData;
        this.consumosData = consumosData;
        this.mesasData = mesasData;
        this.mozosData = mozosData;
        this.se_ConsumeData = se_ConsumeData;
        this.parent = parent;

        // Inicializacion de los mensajes de error
        errMsg1.setVisible(false);
        errMsg2.setVisible(false);
        errMsg3.setVisible(false);
        errMsg4.setVisible(false);

        errMsgMo1.setVisible(false);
        errMsgMo2.setVisible(false);
        errMsgMo3.setVisible(false);
        errMsgMo4.setVisible(false);

        errMsgP1.setVisible(false);
        errMsgP2.setVisible(false);
        errMsgP3.setVisible(false);
        errMsgP4.setVisible(false);
        errMsgP5.setVisible(false);
        errMsgP6.setVisible(false);
        errMsgP7.setVisible(false);

        errMsgMe1.setVisible(false);
        errMsgMe2.setVisible(false);
        errMsgMe3.setVisible(false);

        errMsgSeC1.setVisible(false);
        errMsgSeC2.setVisible(false);

        // Inicializacion de los mensajes de exito
        succesInputConsumo.setVisible(false);
        succesInputMesa.setVisible(false);
        succesInputMozo.setVisible(false);
        succesInputPlato.setVisible(false);
        succesInputSeConsume.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputTabbedPane = new javax.swing.JTabbedPane();
        InputConsumoPane = new javax.swing.JPanel();
        codigoCLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        horaLabel = new javax.swing.JLabel();
        codMesaLabel = new javax.swing.JLabel();
        codigoTField = new javax.swing.JTextField();
        diaTField = new javax.swing.JTextField();
        mesTField = new javax.swing.JTextField();
        anioTField = new javax.swing.JTextField();
        errMsg1 = new javax.swing.JLabel();
        errMsg2 = new javax.swing.JLabel();
        errMsg3 = new javax.swing.JLabel();
        errMsg4 = new javax.swing.JLabel();
        codMesaTField = new javax.swing.JTextField();
        horaTField = new javax.swing.JTextField();
        minTField = new javax.swing.JTextField();
        consumoIngButton = new javax.swing.JButton();
        succesInputConsumo = new javax.swing.JLabel();
        InputMesaPane = new javax.swing.JPanel();
        codigoMeLabel = new javax.swing.JLabel();
        sectorLabel = new javax.swing.JLabel();
        codMozoAtiendeLabel = new javax.swing.JLabel();
        codigoMeTField = new javax.swing.JTextField();
        sectorTField = new javax.swing.JTextField();
        codMozoAtiendeTField = new javax.swing.JTextField();
        errMsgMe1 = new javax.swing.JLabel();
        errMsgMe2 = new javax.swing.JLabel();
        errMsgMe3 = new javax.swing.JLabel();
        MesaIngButton1 = new javax.swing.JButton();
        succesInputMesa = new javax.swing.JLabel();
        InputMozoPane = new javax.swing.JPanel();
        codigoMLabel = new javax.swing.JLabel();
        nombreMLabel = new javax.swing.JLabel();
        domicilioLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        codigoMTField = new javax.swing.JTextField();
        nombreMTField = new javax.swing.JTextField();
        domicilioTField = new javax.swing.JTextField();
        dniTField = new javax.swing.JTextField();
        errMsgMo1 = new javax.swing.JLabel();
        errMsgMo2 = new javax.swing.JLabel();
        errMsgMo3 = new javax.swing.JLabel();
        errMsgMo4 = new javax.swing.JLabel();
        MozoIngButton2 = new javax.swing.JButton();
        succesInputMozo = new javax.swing.JLabel();
        InputPlatoPane = new javax.swing.JPanel();
        codigoPLabel = new javax.swing.JLabel();
        nombrePLabel = new javax.swing.JLabel();
        descripcionLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        costoLabel = new javax.swing.JLabel();
        ventaLabel = new javax.swing.JLabel();
        promocionLabel = new javax.swing.JLabel();
        codigoPTField = new javax.swing.JTextField();
        nombrePTField = new javax.swing.JTextField();
        tipoTField = new javax.swing.JTextField();
        costoTField = new javax.swing.JTextField();
        ventaTField = new javax.swing.JTextField();
        promocionTField = new javax.swing.JTextField();
        descripcionSPane = new javax.swing.JScrollPane();
        descripcionTArea = new javax.swing.JTextArea();
        errMsgP1 = new javax.swing.JLabel();
        errMsgP2 = new javax.swing.JLabel();
        errMsgP3 = new javax.swing.JLabel();
        errMsgP4 = new javax.swing.JLabel();
        errMsgP5 = new javax.swing.JLabel();
        errMsgP6 = new javax.swing.JLabel();
        platoIngButton = new javax.swing.JButton();
        succesInputPlato = new javax.swing.JLabel();
        errMsgP7 = new javax.swing.JLabel();
        InputSe_ConsumePane = new javax.swing.JPanel();
        codConsumoLabel = new javax.swing.JLabel();
        codPlatoLabel = new javax.swing.JLabel();
        codConsumoTField = new javax.swing.JTextField();
        codPlatoTfield = new javax.swing.JTextField();
        errMsgSeC1 = new javax.swing.JLabel();
        errMsgSeC2 = new javax.swing.JLabel();
        seConsumeIngButton4 = new javax.swing.JButton();
        succesInputSeConsume = new javax.swing.JLabel();

        InputConsumoPane.setForeground(new java.awt.Color(255, 0, 0));
        InputConsumoPane.setNextFocusableComponent(InputMesaPane);

        codigoCLabel.setText("Código");

        fechaLabel.setText("Fecha");

        horaLabel.setText("Hora");

        codMesaLabel.setText("Código de la mesa");

        codigoTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTFieldActionPerformed(evt);
            }
        });

        diaTField.setText("<Día>");
        diaTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaTFieldActionPerformed(evt);
            }
        });

        mesTField.setText("<Mes>");
        mesTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesTFieldActionPerformed(evt);
            }
        });

        anioTField.setText("<Año>");
        anioTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioTFieldActionPerformed(evt);
            }
        });

        errMsg1.setForeground(new java.awt.Color(255, 0, 0));
        errMsg1.setText("Debe ser un entero");

        errMsg2.setForeground(new java.awt.Color(255, 0, 0));
        errMsg2.setText("Mensaje de error");

        errMsg3.setForeground(new java.awt.Color(255, 0, 0));
        errMsg3.setText("Mensaje de error");

        errMsg4.setForeground(new java.awt.Color(255, 0, 0));
        errMsg4.setText("Debe ser un entero");

        codMesaTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codMesaTFieldActionPerformed(evt);
            }
        });

        horaTField.setText("<Hs>");
        horaTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaTFieldActionPerformed(evt);
            }
        });

        minTField.setText("<Min>");
        minTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minTFieldActionPerformed(evt);
            }
        });

        consumoIngButton.setText("Ingresar");
        consumoIngButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumoIngButtonActionPerformed(evt);
            }
        });

        succesInputConsumo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        succesInputConsumo.setText("El consumo fue ingresado con exito");

        javax.swing.GroupLayout InputConsumoPaneLayout = new javax.swing.GroupLayout(InputConsumoPane);
        InputConsumoPane.setLayout(InputConsumoPaneLayout);
        InputConsumoPaneLayout.setHorizontalGroup(
                InputConsumoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputConsumoPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InputConsumoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(InputConsumoPaneLayout.createSequentialGroup()
                                                .addGroup(InputConsumoPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(InputConsumoPaneLayout.createSequentialGroup()
                                                                .addGroup(InputConsumoPaneLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(codigoTField,
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(InputConsumoPaneLayout
                                                                                .createSequentialGroup()
                                                                                .addComponent(diaTField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        47,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(mesTField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(InputConsumoPaneLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(InputConsumoPaneLayout
                                                                                .createSequentialGroup()
                                                                                .addComponent(anioTField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(errMsg2))
                                                                        .addComponent(errMsg1)))
                                                        .addGroup(InputConsumoPaneLayout.createSequentialGroup()
                                                                .addComponent(horaTField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(minTField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(errMsg3)))
                                                .addGap(0, 142, Short.MAX_VALUE))
                                        .addGroup(InputConsumoPaneLayout.createSequentialGroup()
                                                .addGroup(InputConsumoPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(InputConsumoPaneLayout.createSequentialGroup()
                                                                .addGroup(InputConsumoPaneLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(InputConsumoPaneLayout
                                                                                .createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                        false)
                                                                                .addComponent(codigoCLabel,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(fechaLabel,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(horaLabel,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(codMesaLabel,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE))
                                                                        .addGroup(InputConsumoPaneLayout
                                                                                .createSequentialGroup()
                                                                                .addComponent(codMesaTField,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        104,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(errMsg4)))
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                InputConsumoPaneLayout.createSequentialGroup()
                                                                        .addComponent(succesInputConsumo)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(consumoIngButton)))
                                                .addContainerGap()))));
        InputConsumoPaneLayout.setVerticalGroup(
                InputConsumoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputConsumoPaneLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(codigoCLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputConsumoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codigoTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsg1))
                                .addGap(20, 20, 20)
                                .addComponent(fechaLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputConsumoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(diaTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsg2)
                                        .addComponent(mesTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(anioTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(horaLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputConsumoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(errMsg3)
                                        .addComponent(horaTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(minTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(codMesaLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputConsumoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codMesaTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsg4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154,
                                        Short.MAX_VALUE)
                                .addGroup(InputConsumoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(consumoIngButton)
                                        .addComponent(succesInputConsumo))
                                .addContainerGap()));

        InputTabbedPane.addTab("Consumo", InputConsumoPane);

        InputMesaPane.setNextFocusableComponent(InputMozoPane);

        codigoMeLabel.setText("Código");

        sectorLabel.setText("Sector");

        codMozoAtiendeLabel.setText("Código de mozo encargado");

        codigoMeTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoMeTFieldActionPerformed(evt);
            }
        });

        sectorTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectorTFieldActionPerformed(evt);
            }
        });

        codMozoAtiendeTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codMozoAtiendeTFieldActionPerformed(evt);
            }
        });

        errMsgMe1.setForeground(new java.awt.Color(255, 0, 0));
        errMsgMe1.setText("Debe ser un entero");

        errMsgMe2.setForeground(new java.awt.Color(255, 0, 0));
        errMsgMe2.setText("Mensaje de error");

        errMsgMe3.setForeground(new java.awt.Color(255, 0, 0));
        errMsgMe3.setText("Debe ser un entero");

        MesaIngButton1.setText("Ingresar");
        MesaIngButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesaIngButton1ActionPerformed(evt);
            }
        });

        succesInputMesa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        succesInputMesa.setText("La mesa fue ingresada con exito");

        javax.swing.GroupLayout InputMesaPaneLayout = new javax.swing.GroupLayout(InputMesaPane);
        InputMesaPane.setLayout(InputMesaPaneLayout);
        InputMesaPaneLayout.setHorizontalGroup(
                InputMesaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputMesaPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InputMesaPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(InputMesaPaneLayout.createSequentialGroup()
                                                .addGroup(InputMesaPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(codigoMeLabel)
                                                        .addComponent(sectorLabel)
                                                        .addComponent(codMozoAtiendeTField)
                                                        .addComponent(codMozoAtiendeLabel,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(sectorTField)
                                                        .addComponent(codigoMeTField))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(InputMesaPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(errMsgMe3)
                                                        .addComponent(errMsgMe1)
                                                        .addComponent(errMsgMe2))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputMesaPaneLayout
                                                .createSequentialGroup()
                                                .addComponent(succesInputMesa)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(MesaIngButton1)))
                                .addContainerGap()));
        InputMesaPaneLayout.setVerticalGroup(
                InputMesaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputMesaPaneLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(codigoMeLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputMesaPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codigoMeTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgMe1))
                                .addGap(20, 20, 20)
                                .addComponent(sectorLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputMesaPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sectorTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgMe2))
                                .addGap(20, 20, 20)
                                .addComponent(codMozoAtiendeLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputMesaPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codMozoAtiendeTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgMe3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(InputMesaPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(MesaIngButton1)
                                        .addComponent(succesInputMesa))
                                .addContainerGap()));

        InputTabbedPane.addTab("Mesa", InputMesaPane);

        InputMozoPane.setNextFocusableComponent(InputPlatoPane);

        codigoMLabel.setText("Código");

        nombreMLabel.setText("Nombre y Apellido");

        domicilioLabel.setText("Domicilio");

        dniLabel.setText("DNI");

        codigoMTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoMTFieldActionPerformed(evt);
            }
        });

        nombreMTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMTFieldActionPerformed(evt);
            }
        });

        domicilioTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domicilioTFieldActionPerformed(evt);
            }
        });

        dniTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTFieldActionPerformed(evt);
            }
        });

        errMsgMo1.setForeground(new java.awt.Color(255, 0, 0));
        errMsgMo1.setText("Debe ser un entero");

        errMsgMo2.setForeground(new java.awt.Color(255, 0, 0));
        errMsgMo2.setText("Mensaje de error");

        errMsgMo3.setForeground(new java.awt.Color(255, 0, 0));
        errMsgMo3.setText("Mensaje de error");

        errMsgMo4.setForeground(new java.awt.Color(255, 0, 0));
        errMsgMo4.setText("Debe ser un entero");

        MozoIngButton2.setText("Ingresar");
        MozoIngButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MozoIngButton2ActionPerformed(evt);
            }
        });

        succesInputMozo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        succesInputMozo.setText("El mozo fue ingresado con exito");

        javax.swing.GroupLayout InputMozoPaneLayout = new javax.swing.GroupLayout(InputMozoPane);
        InputMozoPane.setLayout(InputMozoPaneLayout);
        InputMozoPaneLayout.setHorizontalGroup(
                InputMozoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputMozoPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InputMozoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(InputMozoPaneLayout.createSequentialGroup()
                                                .addGroup(InputMozoPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(codigoMLabel)
                                                        .addComponent(nombreMLabel)
                                                        .addComponent(domicilioLabel)
                                                        .addComponent(dniLabel)
                                                        .addComponent(codigoMTField,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 149,
                                                                Short.MAX_VALUE)
                                                        .addComponent(nombreMTField)
                                                        .addComponent(domicilioTField)
                                                        .addComponent(dniTField))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(InputMozoPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(errMsgMo1)
                                                        .addComponent(errMsgMo4)
                                                        .addComponent(errMsgMo3)
                                                        .addComponent(errMsgMo2))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputMozoPaneLayout
                                                .createSequentialGroup()
                                                .addComponent(succesInputMozo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(MozoIngButton2)))
                                .addContainerGap()));
        InputMozoPaneLayout.setVerticalGroup(
                InputMozoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputMozoPaneLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(codigoMLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputMozoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codigoMTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgMo1))
                                .addGap(20, 20, 20)
                                .addComponent(nombreMLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputMozoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nombreMTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgMo2))
                                .addGap(20, 20, 20)
                                .addComponent(domicilioLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputMozoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(domicilioTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgMo3))
                                .addGap(20, 20, 20)
                                .addComponent(dniLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputMozoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dniTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgMo4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(InputMozoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(MozoIngButton2)
                                        .addComponent(succesInputMozo))
                                .addContainerGap()));

        InputTabbedPane.addTab("Mozo", InputMozoPane);

        InputPlatoPane.setNextFocusableComponent(InputSe_ConsumePane);

        codigoPLabel.setText("Código");

        nombrePLabel.setText("Nombre");

        descripcionLabel.setText("Descripción");

        tipoLabel.setText("Tipo");

        costoLabel.setText("Costo");

        ventaLabel.setText("Precio de Venta");

        promocionLabel.setText("Precio de Promoción");

        codigoPTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoPTFieldActionPerformed(evt);
            }
        });

        nombrePTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePTFieldActionPerformed(evt);
            }
        });

        tipoTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoTFieldActionPerformed(evt);
            }
        });

        costoTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoTFieldActionPerformed(evt);
            }
        });

        ventaTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaTFieldActionPerformed(evt);
            }
        });

        promocionTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promocionTFieldActionPerformed(evt);
            }
        });

        descripcionTArea.setColumns(20);
        descripcionTArea.setRows(5);
        descripcionTArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descripcionTAreaKeyPressed(evt);
            }
        });
        descripcionSPane.setViewportView(descripcionTArea);

        errMsgP1.setForeground(new java.awt.Color(255, 0, 0));
        errMsgP1.setText("Debe ser un entero");

        errMsgP2.setForeground(new java.awt.Color(255, 0, 0));
        errMsgP2.setText("Mensaje de error");

        errMsgP3.setForeground(new java.awt.Color(255, 0, 0));
        errMsgP3.setText("Mensaje de error");

        errMsgP4.setForeground(new java.awt.Color(255, 0, 0));
        errMsgP4.setText("Mensaje de error");

        errMsgP5.setForeground(new java.awt.Color(255, 0, 0));
        errMsgP5.setText("Debe ser un entero");

        errMsgP6.setForeground(new java.awt.Color(255, 0, 0));
        errMsgP6.setText("Debe ser un entero");

        platoIngButton.setText("Ingresar");
        platoIngButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platoIngButtonActionPerformed(evt);
            }
        });

        succesInputPlato.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        succesInputPlato.setText("El plato fue ingresado con exito");

        errMsgP7.setForeground(new java.awt.Color(255, 0, 0));
        errMsgP7.setText("Debe ser un entero");

        javax.swing.GroupLayout InputPlatoPaneLayout = new javax.swing.GroupLayout(InputPlatoPane);
        InputPlatoPane.setLayout(InputPlatoPaneLayout);
        InputPlatoPaneLayout.setHorizontalGroup(
                InputPlatoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputPlatoPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InputPlatoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(InputPlatoPaneLayout.createSequentialGroup()
                                                .addGroup(InputPlatoPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(descripcionLabel)
                                                        .addComponent(costoLabel)
                                                        .addComponent(tipoLabel)
                                                        .addGroup(InputPlatoPaneLayout.createSequentialGroup()
                                                                .addComponent(descripcionSPane,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(errMsgP3)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(InputPlatoPaneLayout.createSequentialGroup()
                                                .addGroup(InputPlatoPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(InputPlatoPaneLayout.createSequentialGroup()
                                                                .addComponent(succesInputPlato)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(platoIngButton))
                                                        .addGroup(InputPlatoPaneLayout.createSequentialGroup()
                                                                .addGroup(InputPlatoPaneLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(promocionLabel)
                                                                        .addGroup(InputPlatoPaneLayout
                                                                                .createSequentialGroup()
                                                                                .addGroup(InputPlatoPaneLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                        .addComponent(codigoPLabel)
                                                                                        .addComponent(nombrePLabel)
                                                                                        .addComponent(codigoPTField,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                150, Short.MAX_VALUE)
                                                                                        .addComponent(nombrePTField))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(InputPlatoPaneLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(errMsgP1)
                                                                                        .addComponent(errMsgP2)))
                                                                        .addGroup(InputPlatoPaneLayout
                                                                                .createSequentialGroup()
                                                                                .addGroup(InputPlatoPaneLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                false)
                                                                                        .addComponent(promocionTField,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                150, Short.MAX_VALUE)
                                                                                        .addComponent(ventaTField,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(costoTField,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(tipoTField,
                                                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(InputPlatoPaneLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(errMsgP6)
                                                                                        .addComponent(errMsgP5)
                                                                                        .addComponent(errMsgP4)
                                                                                        .addComponent(errMsgP7)))
                                                                        .addComponent(ventaLabel))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap()))));
        InputPlatoPaneLayout.setVerticalGroup(
                InputPlatoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputPlatoPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(codigoPLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InputPlatoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codigoPTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgP1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombrePLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InputPlatoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nombrePTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgP2))
                                .addGap(9, 9, 9)
                                .addComponent(descripcionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InputPlatoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(InputPlatoPaneLayout.createSequentialGroup()
                                                .addComponent(descripcionSPane, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                InputPlatoPaneLayout.createSequentialGroup()
                                                        .addComponent(errMsgP3)
                                                        .addGap(40, 40, 40)))
                                .addComponent(tipoLabel)
                                .addGroup(InputPlatoPaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(InputPlatoPaneLayout.createSequentialGroup()
                                                .addGroup(InputPlatoPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(tipoTField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(errMsgP4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(costoLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(InputPlatoPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(costoTField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(errMsgP5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ventaLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(InputPlatoPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ventaTField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(errMsgP6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(promocionLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(InputPlatoPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(promocionTField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(errMsgP7))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputPlatoPaneLayout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(InputPlatoPaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(platoIngButton)
                                                        .addComponent(succesInputPlato,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 19,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap()));

        InputTabbedPane.addTab("Plato", InputPlatoPane);

        InputSe_ConsumePane.setNextFocusableComponent(InputMozoPane);

        codConsumoLabel.setText("Código de consumo");

        codPlatoLabel.setText("Código de plato");

        codConsumoTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codConsumoTFieldActionPerformed(evt);
            }
        });

        codPlatoTfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codPlatoTfieldActionPerformed(evt);
            }
        });

        errMsgSeC1.setForeground(new java.awt.Color(255, 0, 0));
        errMsgSeC1.setText("Debe ser un entero");

        errMsgSeC2.setForeground(new java.awt.Color(255, 0, 0));
        errMsgSeC2.setText("Debe ser un entero");

        seConsumeIngButton4.setText("Ingresar");
        seConsumeIngButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seConsumeIngButton4ActionPerformed(evt);
            }
        });

        succesInputSeConsume.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        succesInputSeConsume.setText("El plato fue ingresado al consumo con exito");

        javax.swing.GroupLayout InputSe_ConsumePaneLayout = new javax.swing.GroupLayout(InputSe_ConsumePane);
        InputSe_ConsumePane.setLayout(InputSe_ConsumePaneLayout);
        InputSe_ConsumePaneLayout.setHorizontalGroup(
                InputSe_ConsumePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputSe_ConsumePaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InputSe_ConsumePaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(InputSe_ConsumePaneLayout.createSequentialGroup()
                                                .addGroup(InputSe_ConsumePaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(codConsumoLabel)
                                                        .addComponent(codPlatoLabel)
                                                        .addComponent(codConsumoTField,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 150,
                                                                Short.MAX_VALUE)
                                                        .addComponent(codPlatoTfield))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(InputSe_ConsumePaneLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(errMsgSeC2)
                                                        .addComponent(errMsgSeC1))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InputSe_ConsumePaneLayout
                                                .createSequentialGroup()
                                                .addComponent(succesInputSeConsume)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(seConsumeIngButton4)))
                                .addContainerGap()));
        InputSe_ConsumePaneLayout.setVerticalGroup(
                InputSe_ConsumePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InputSe_ConsumePaneLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(codConsumoLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputSe_ConsumePaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codConsumoTField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgSeC1))
                                .addGap(20, 20, 20)
                                .addComponent(codPlatoLabel)
                                .addGap(10, 10, 10)
                                .addGroup(InputSe_ConsumePaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codPlatoTfield, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errMsgSeC2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(InputSe_ConsumePaneLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(seConsumeIngButton4)
                                        .addComponent(succesInputSeConsume))
                                .addContainerGap()));

        InputTabbedPane.addTab("Se Consume", InputSe_ConsumePane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(InputTabbedPane));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(InputTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 520,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoPTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_codigoPTFieldActionPerformed
        nombrePTField.requestFocus();
    }// GEN-LAST:event_codigoPTFieldActionPerformed

    private void nombrePTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nombrePTFieldActionPerformed
        descripcionTArea.requestFocus();
    }// GEN-LAST:event_nombrePTFieldActionPerformed

    private void tipoTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tipoTFieldActionPerformed
        costoTField.requestFocus();
    }// GEN-LAST:event_tipoTFieldActionPerformed

    private void costoTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_costoTFieldActionPerformed
        ventaTField.requestFocus();
    }// GEN-LAST:event_costoTFieldActionPerformed

    private void ventaTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ventaTFieldActionPerformed
        promocionTField.requestFocus();
    }// GEN-LAST:event_ventaTFieldActionPerformed

    private void descripcionTAreaKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_descripcionTAreaKeyPressed
        if (evt.getKeyChar() == '\t' /* || evt.getKeyChar() == '\n' */) {// Para salir del TextArea con Enter tambien
            tipoTField.requestFocus();
        }
    }// GEN-LAST:event_descripcionTAreaKeyPressed

    private void MozoIngButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MozoIngButton2ActionPerformed
        cargarMozo();
    }// GEN-LAST:event_MozoIngButton2ActionPerformed

    private void dniTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dniTFieldActionPerformed
        cargarMozo();
    }// GEN-LAST:event_dniTFieldActionPerformed

    private void codMozoAtiendeTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_codMozoAtiendeTFieldActionPerformed
        cargarMesa();
    }// GEN-LAST:event_codMozoAtiendeTFieldActionPerformed

    private void MesaIngButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MesaIngButton1ActionPerformed
        cargarMesa();
    }// GEN-LAST:event_MesaIngButton1ActionPerformed

    private void codMesaTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_codMesaTFieldActionPerformed
        cargarConsumo();
    }// GEN-LAST:event_codMesaTFieldActionPerformed

    private void consumoIngButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_consumoIngButtonActionPerformed
        cargarConsumo();
    }// GEN-LAST:event_consumoIngButtonActionPerformed

    private void codConsumoTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_codConsumoTFieldActionPerformed
        codPlatoTfield.requestFocus();
    }// GEN-LAST:event_codConsumoTFieldActionPerformed

    private void codPlatoTfieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_codPlatoTfieldActionPerformed
        cargarSeConsume();
    }// GEN-LAST:event_codPlatoTfieldActionPerformed

    private void seConsumeIngButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_seConsumeIngButton4ActionPerformed
        cargarSeConsume();
    }// GEN-LAST:event_seConsumeIngButton4ActionPerformed

    private void codigoMTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_codigoMTFieldActionPerformed
        nombreMTField.requestFocus();
    }// GEN-LAST:event_codigoMTFieldActionPerformed

    private void nombreMTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nombreMTFieldActionPerformed
        domicilioTField.requestFocus();
    }// GEN-LAST:event_nombreMTFieldActionPerformed

    private void domicilioTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_domicilioTFieldActionPerformed
        dniTField.requestFocus();
    }// GEN-LAST:event_domicilioTFieldActionPerformed

    private void codigoMeTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_codigoMeTFieldActionPerformed
        sectorTField.requestFocus();
    }// GEN-LAST:event_codigoMeTFieldActionPerformed

    private void sectorTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sectorTFieldActionPerformed
        codMozoAtiendeTField.requestFocus();
    }// GEN-LAST:event_sectorTFieldActionPerformed

    private void codigoTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_codigoTFieldActionPerformed
        diaTField.requestFocus();
    }// GEN-LAST:event_codigoTFieldActionPerformed

    private void diaTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_diaTFieldActionPerformed
        mesTField.requestFocus();
    }// GEN-LAST:event_diaTFieldActionPerformed

    private void mesTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_mesTFieldActionPerformed
        anioTField.requestFocus();
    }// GEN-LAST:event_mesTFieldActionPerformed

    private void anioTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_anioTFieldActionPerformed
        horaTField.requestFocus();
    }// GEN-LAST:event_anioTFieldActionPerformed

    private void horaTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_horaTFieldActionPerformed
        minTField.requestFocus();
    }// GEN-LAST:event_horaTFieldActionPerformed

    private void minTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_minTFieldActionPerformed
        codMesaTField.requestFocus();
    }// GEN-LAST:event_minTFieldActionPerformed

    private void platoIngButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_platoIngButtonActionPerformed
        cargarPlato();
    }// GEN-LAST:event_platoIngButtonActionPerformed

    private void promocionTFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_promocionTFieldActionPerformed
        cargarPlato();
    }// GEN-LAST:event_promocionTFieldActionPerformed

    private void cargarPlato() {
        int codigo = 0, costo = 0, venta = 0, promocion = 0;
        String descripcion, tipo, nombre;
        boolean correcto = true;

        nombre = nombrePTField.getText();
        descripcion = descripcionTArea.getText();
        tipo = tipoTField.getText();

        succesInputPlato.setVisible(false);

        // Controles de datos
        try {
            codigo = Integer.parseInt(codigoPTField.getText());
            errMsgP1.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsgP1.setVisible(true);
        }

        if (nombre.matches("")) {
            correcto = false;
            errMsgP2.setText("*Obligatorio");
            errMsgP2.setVisible(true);
        } else if (!(nombre.matches("\\D+"))) {
            correcto = false;
            errMsgP2.setText("No debe contener números");
            errMsgP2.setVisible(true);
        } else {
            errMsgP2.setVisible(false);
        }

        if (descripcion.matches("")) {
            correcto = false;
            errMsgP3.setText("*Obligatorio");
            errMsgP3.setVisible(true);
        } else if (!(descripcion.matches("\\D+"))) {
            correcto = false;
            errMsgP3.setText("No debe contener números");
            errMsgP3.setVisible(true);
        } else {
            errMsgP3.setVisible(false);
        }

        if (tipo.matches("")) {
            correcto = false;
            errMsgP4.setText("*Obligatorio");
            errMsgP4.setVisible(true);
        } else if (!(tipo.matches("\\D+"))) {
            correcto = false;
            errMsgP4.setText("No debe contener números");
            errMsgP4.setVisible(true);
        } else {
            errMsgP4.setVisible(false);
        }

        try {
            costo = Integer.parseInt(costoTField.getText());
            errMsgP5.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsgP5.setVisible(true);
        }

        try {
            errMsgP6.setVisible(false);
            venta = Integer.parseInt(ventaTField.getText());
        } catch (NumberFormatException e) {
            correcto = false;
            errMsgP6.setVisible(true);
        }

        try {
            errMsgP7.setVisible(false);
            promocion = Integer.parseInt(promocionTField.getText());
        } catch (NumberFormatException e) {
            correcto = false;
            errMsgP7.setVisible(true);
        }

        if (correcto) {
            Platos plato = new Platos(codigo, costo, venta, promocion, descripcion, nombre, tipo);

            if (platosData.insertPlato(plato)) {
                // Mensaje de exito de la operacion
                succesInputPlato.setVisible(true);
            }

            // Reseteo de los mensajes de error
            errMsgP1.setVisible(false);
            errMsgP2.setVisible(false);
            errMsgP3.setVisible(false);
            errMsgP4.setVisible(false);
            errMsgP5.setVisible(false);
            errMsgP6.setVisible(false);
            errMsgP7.setVisible(false);

            // Reseteo de los campos de texto
            codigoPTField.setText("");
            nombrePTField.setText("");
            descripcionTArea.setText("");
            tipoTField.setText("");
            costoTField.setText("");
            ventaTField.setText("");
            promocionTField.setText("");
        }
    }

    private void cargarMozo() {
        int codigo = 0, dni = 0;
        String nombre, domicilio;
        boolean correcto = true;

        nombre = nombreMTField.getText();
        domicilio = domicilioTField.getText();

        succesInputMozo.setVisible(false);

        // Controles de datos
        try {
            codigo = Integer.parseInt(codigoMTField.getText());
            errMsgMo1.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsgMo1.setVisible(true);
        }

        if (nombre.matches("")) {
            correcto = false;
            errMsgMo2.setText("*Obligatorio");
            errMsgMo2.setVisible(true);
        } else if (!(nombre.matches("\\D+"))) {
            correcto = false;
            errMsgMo2.setText("No debe contener números");
            errMsgMo2.setVisible(true);
        } else {
            errMsgMo2.setVisible(false);
        }

        if (domicilio.matches("")) {
            correcto = false;
            errMsgMo3.setText("*Obligatorio");
            errMsgMo3.setVisible(true);
        } else {
            errMsgMo3.setVisible(false);
        }

        try {
            dni = Integer.parseInt(dniTField.getText());
            errMsgMo4.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsgMo4.setVisible(true);
        }

        if (correcto) {
            Mozos mozo = new Mozos(codigo, nombre, domicilio, dni);

            if (mozosData.insertMozo(mozo)) {
                // Mensaje de exito de la operacion
                succesInputMozo.setVisible(true);

                // Reseteo de los mensajes de error
                errMsgMo1.setVisible(false);
                errMsgMo2.setVisible(false);
                errMsgMo3.setVisible(false);
                errMsgMo4.setVisible(false);

                // Reseteo de los campos de texto
                codigoMTField.setText("");
                nombreMTField.setText("");
                domicilioTField.setText("");
                dniTField.setText("");
            }
        }
    }

    private void cargarMesa() {
        int codigo = 0, codigoMozo = 0;
        String sector = sectorTField.getText();
        boolean correcto = true;

        succesInputMesa.setVisible(false);

        try {
            codigo = Integer.parseInt(codigoMeTField.getText());
            errMsgMe1.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsgMe1.setVisible(true);
        }

        if (sector.matches("")) {
            correcto = false;
            errMsgMe2.setText("*Obligatorio");
            errMsgMe2.setVisible(true);
        } else if (!(sector.matches("\\D+"))) {
            correcto = false;
            errMsgMe2.setText("No debe contener números");
            errMsgMe2.setVisible(true);
        } else {
            errMsgMe2.setVisible(false);
        }

        try {
            codigoMozo = Integer.parseInt(codMozoAtiendeTField.getText());
            errMsgMe3.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsgMe3.setVisible(true);
        }

        if (correcto) {
            Mesas mesa = new Mesas(codigo, codigoMozo, sector);

            if (mesasData.insertMesa(mesa)) {
                // Mensaje de exito de la operacion
                succesInputMesa.setVisible(true);

                // Reseteo de los mensajes de error
                errMsgMo1.setVisible(false);
                errMsgMo2.setVisible(false);
                errMsgMo3.setVisible(false);
                errMsgMo4.setVisible(false);

                // Reseteo de los campos de texto
                codigoMTField.setText("");
                nombreMTField.setText("");
                domicilioTField.setText("");
                dniTField.setText("");
            }
        }
    }

    private void cargarConsumo() {
        int codigo = 0, codigoMesa = 0;
        LocalDate fecha = null;
        LocalTime hora = null;
        boolean correcto = true;

        succesInputConsumo.setVisible(false);

        try {
            codigo = Integer.parseInt(codigoTField.getText());
            errMsg1.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsg1.setVisible(true);
        }

        try {
            int dia = Integer.parseInt(diaTField.getText());
            int mes = Integer.parseInt(mesTField.getText());
            int anio = Integer.parseInt(anioTField.getText());

            fecha = LocalDate.of(anio, mes, dia);
            errMsg2.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsg2.setText("Deben ser enteros");
            errMsg2.setVisible(true);
        } catch (DateTimeException e) {
            correcto = false;
            errMsg2.setText("Fecha inválida");
            errMsg2.setVisible(true);
        }

        try {
            int h = Integer.parseInt(horaTField.getText());
            int m = Integer.parseInt(minTField.getText());
            hora = LocalTime.of(h, m);
            errMsg3.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsg3.setText("Deben ser enteros");
            errMsg3.setVisible(true);
        } catch (DateTimeException e) {
            correcto = false;
            errMsg3.setText("Hora inválida");
            errMsg3.setVisible(true);
        }

        try {
            codigoMesa = Integer.parseInt(codMesaTField.getText());
            errMsg4.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsg4.setVisible(true);
        }

        if (correcto) {
            Consumos consumo = new Consumos(codigo, codigoMesa, fecha, hora);

            if (consumosData.insertConsumo(consumo)) {
                // Mensaje de exito de la operacion
                succesInputConsumo.setVisible(true);

                // Reseteo de los mensajes de error
                errMsg1.setVisible(false);
                errMsg2.setVisible(false);
                errMsg3.setVisible(false);
                errMsg4.setVisible(false);

                // Reseteo de los campos de texto
                codigoTField.setText("");
                diaTField.setText("");
                mesTField.setText("");
                anioTField.setText("");
                horaTField.setText("");
                minTField.setText("");
                codMesaTField.setText("");
            }
        }
    }

    private void cargarSeConsume() {
        int codigoConsumo = 0, codigoPlato = 0;
        boolean correcto = true;

        succesInputSeConsume.setVisible(false);

        try {
            codigoConsumo = Integer.parseInt(codConsumoTField.getText());
            errMsgSeC1.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsgSeC1.setVisible(true);
        }

        try {
            codigoPlato = Integer.parseInt(codPlatoTfield.getText());
            errMsgSeC2.setVisible(false);
        } catch (NumberFormatException e) {
            correcto = false;
            errMsgSeC2.setVisible(true);
        }

        if (correcto) {
            Se_Consume se_Consume = new Se_Consume(codigoConsumo, codigoPlato);

            if (se_ConsumeData.insertConsumo(se_Consume)) {
                // Mensaje de exito de la operacion
                succesInputSeConsume.setVisible(true);

                // Reseteo de los mensajes de error
                errMsgSeC1.setVisible(false);
                errMsgSeC2.setVisible(false);

                // Reseteo de los campos de texto
                codConsumoTField.setText("");
                codPlatoTfield.setText("");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InputConsumoPane;
    private javax.swing.JPanel InputMesaPane;
    private javax.swing.JPanel InputMozoPane;
    private javax.swing.JPanel InputPlatoPane;
    private javax.swing.JPanel InputSe_ConsumePane;
    private javax.swing.JTabbedPane InputTabbedPane;
    private javax.swing.JButton MesaIngButton1;
    private javax.swing.JButton MozoIngButton2;
    private javax.swing.JTextField anioTField;
    private javax.swing.JLabel codConsumoLabel;
    private javax.swing.JTextField codConsumoTField;
    private javax.swing.JLabel codMesaLabel;
    private javax.swing.JTextField codMesaTField;
    private javax.swing.JLabel codMozoAtiendeLabel;
    private javax.swing.JTextField codMozoAtiendeTField;
    private javax.swing.JLabel codPlatoLabel;
    private javax.swing.JTextField codPlatoTfield;
    private javax.swing.JLabel codigoCLabel;
    private javax.swing.JLabel codigoMLabel;
    private javax.swing.JTextField codigoMTField;
    private javax.swing.JLabel codigoMeLabel;
    private javax.swing.JTextField codigoMeTField;
    private javax.swing.JLabel codigoPLabel;
    private javax.swing.JTextField codigoPTField;
    private javax.swing.JTextField codigoTField;
    private javax.swing.JButton consumoIngButton;
    private javax.swing.JLabel costoLabel;
    private javax.swing.JTextField costoTField;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JScrollPane descripcionSPane;
    private javax.swing.JTextArea descripcionTArea;
    private javax.swing.JTextField diaTField;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniTField;
    private javax.swing.JLabel domicilioLabel;
    private javax.swing.JTextField domicilioTField;
    private javax.swing.JLabel errMsg1;
    private javax.swing.JLabel errMsg2;
    private javax.swing.JLabel errMsg3;
    private javax.swing.JLabel errMsg4;
    private javax.swing.JLabel errMsgMe1;
    private javax.swing.JLabel errMsgMe2;
    private javax.swing.JLabel errMsgMe3;
    private javax.swing.JLabel errMsgMo1;
    private javax.swing.JLabel errMsgMo2;
    private javax.swing.JLabel errMsgMo3;
    private javax.swing.JLabel errMsgMo4;
    private javax.swing.JLabel errMsgP1;
    private javax.swing.JLabel errMsgP2;
    private javax.swing.JLabel errMsgP3;
    private javax.swing.JLabel errMsgP4;
    private javax.swing.JLabel errMsgP5;
    private javax.swing.JLabel errMsgP6;
    private javax.swing.JLabel errMsgP7;
    private javax.swing.JLabel errMsgSeC1;
    private javax.swing.JLabel errMsgSeC2;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel horaLabel;
    private javax.swing.JTextField horaTField;
    private javax.swing.JTextField mesTField;
    private javax.swing.JTextField minTField;
    private javax.swing.JLabel nombreMLabel;
    private javax.swing.JTextField nombreMTField;
    private javax.swing.JLabel nombrePLabel;
    private javax.swing.JTextField nombrePTField;
    private javax.swing.JButton platoIngButton;
    private javax.swing.JLabel promocionLabel;
    private javax.swing.JTextField promocionTField;
    private javax.swing.JButton seConsumeIngButton4;
    private javax.swing.JLabel sectorLabel;
    private javax.swing.JTextField sectorTField;
    private javax.swing.JLabel succesInputConsumo;
    private javax.swing.JLabel succesInputMesa;
    private javax.swing.JLabel succesInputMozo;
    private javax.swing.JLabel succesInputPlato;
    private javax.swing.JLabel succesInputSeConsume;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField tipoTField;
    private javax.swing.JLabel ventaLabel;
    private javax.swing.JTextField ventaTField;
    // End of variables declaration//GEN-END:variables
}
