/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.tpmaquianasql.View;

import com.mycompany.tpmaquianasql.Controler.ConsumosData;
import com.mycompany.tpmaquianasql.Controler.MesasData;
import com.mycompany.tpmaquianasql.Controler.MozosData;
import com.mycompany.tpmaquianasql.Controler.PlatosData;
import com.mycompany.tpmaquianasql.Controler.Se_ConsumeData;

/**
 *
 * @author ivanb
 */
public class TablesIJFrame extends javax.swing.JInternalFrame {

    private ConsumosData consumosData;
    private MesasData mesasData;
    private MozosData mozosData;
    private PlatosData platosData;
    private Se_ConsumeData se_ConsumeData;

    /**
     * Creates new form TablesIJFrame
     */
    public TablesIJFrame(ConsumosData consumosData, MesasData mesasData, MozosData mozosData, PlatosData platosData,
            Se_ConsumeData se_ConsumeData) {
        initComponents();

        this.platosData = platosData;
        this.consumosData = consumosData;
        this.mesasData = mesasData;
        this.mozosData = mozosData;
        this.se_ConsumeData = se_ConsumeData;

        setTables();
    }

    public void setTables() {
        this.consumosTable.setModel(consumosData.getConsumosTable());
        this.mesasTable.setModel(mesasData.getMesasTable());
        this.mozosTable.setModel(mozosData.getMozosTable());
        this.platosTable.setModel(platosData.getPlatosTable());
        this.se_ConsumeTable.setModel(se_ConsumeData.getSeConsumeTable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableTabbedPane = new javax.swing.JTabbedPane();
        tableConsumoPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consumosTable = new javax.swing.JTable();
        tableMesaPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mesasTable = new javax.swing.JTable();
        tableMozoPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mozosTable = new javax.swing.JTable();
        tablePlatoPane = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        platosTable = new javax.swing.JTable();
        tableSe_ConsumePane = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        se_ConsumeTable = new javax.swing.JTable();

        tableConsumoPane.setForeground(new java.awt.Color(255, 0, 0));

        consumosTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(consumosTable);

        javax.swing.GroupLayout tableConsumoPaneLayout = new javax.swing.GroupLayout(tableConsumoPane);
        tableConsumoPane.setLayout(tableConsumoPaneLayout);
        tableConsumoPaneLayout.setHorizontalGroup(
                tableConsumoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE));
        tableConsumoPaneLayout.setVerticalGroup(
                tableConsumoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE));

        TableTabbedPane.addTab("Consumo", tableConsumoPane);

        mesasTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane2.setViewportView(mesasTable);

        javax.swing.GroupLayout tableMesaPaneLayout = new javax.swing.GroupLayout(tableMesaPane);
        tableMesaPane.setLayout(tableMesaPaneLayout);
        tableMesaPaneLayout.setHorizontalGroup(
                tableMesaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE));
        tableMesaPaneLayout.setVerticalGroup(
                tableMesaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE));

        TableTabbedPane.addTab("Mesa", tableMesaPane);

        mozosTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane3.setViewportView(mozosTable);

        javax.swing.GroupLayout tableMozoPaneLayout = new javax.swing.GroupLayout(tableMozoPane);
        tableMozoPane.setLayout(tableMozoPaneLayout);
        tableMozoPaneLayout.setHorizontalGroup(
                tableMozoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE));
        tableMozoPaneLayout.setVerticalGroup(
                tableMozoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE));

        TableTabbedPane.addTab("Mozo", tableMozoPane);

        platosTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane4.setViewportView(platosTable);

        javax.swing.GroupLayout tablePlatoPaneLayout = new javax.swing.GroupLayout(tablePlatoPane);
        tablePlatoPane.setLayout(tablePlatoPaneLayout);
        tablePlatoPaneLayout.setHorizontalGroup(
                tablePlatoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE));
        tablePlatoPaneLayout.setVerticalGroup(
                tablePlatoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE));

        TableTabbedPane.addTab("Plato", tablePlatoPane);

        se_ConsumeTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane5.setViewportView(se_ConsumeTable);

        javax.swing.GroupLayout tableSe_ConsumePaneLayout = new javax.swing.GroupLayout(tableSe_ConsumePane);
        tableSe_ConsumePane.setLayout(tableSe_ConsumePaneLayout);
        tableSe_ConsumePaneLayout.setHorizontalGroup(
                tableSe_ConsumePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE));
        tableSe_ConsumePaneLayout.setVerticalGroup(
                tableSe_ConsumePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE));

        TableTabbedPane.addTab("Se Consume", tableSe_ConsumePane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TableTabbedPane));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TableTabbedPane)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TableTabbedPane;
    private javax.swing.JTable consumosTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable mesasTable;
    private javax.swing.JTable mozosTable;
    private javax.swing.JTable platosTable;
    private javax.swing.JTable se_ConsumeTable;
    private javax.swing.JPanel tableConsumoPane;
    private javax.swing.JPanel tableMesaPane;
    private javax.swing.JPanel tableMozoPane;
    private javax.swing.JPanel tablePlatoPane;
    private javax.swing.JPanel tableSe_ConsumePane;
    // End of variables declaration//GEN-END:variables
}
