/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tpmaquianasql.View.ingresar;

import com.mycompany.tpmaquianasql.Controler.PlatosData;

/**
 *
 * @author ivanb
 */
public class PlatoPane extends javax.swing.JPanel {

    private PlatosData platosData;

    /**
     * Creates new form Plato
     */
    public PlatoPane(PlatosData platosData) {
        initComponents();
        
        this.platosData = platosData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoLable = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        descripcionLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        costoLabel = new javax.swing.JLabel();
        ventaLabel = new javax.swing.JLabel();
        promocionLabel = new javax.swing.JLabel();
        tipoField = new javax.swing.JTextField();
        costoField = new javax.swing.JTextField();
        ventaField = new javax.swing.JTextField();
        promocionField = new javax.swing.JTextField();
        descipcionSPane = new javax.swing.JScrollPane();
        descripcionTArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(650, 510));

        codigoLable.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        codigoLable.setForeground(new java.awt.Color(0, 0, 0));
        codigoLable.setText("Código");

        codigoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        codigoField.setText("Ingrese el codigo del plato");
        codigoField.setBorder(null);
        codigoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoFieldActionPerformed(evt);
            }
        });

        nombreLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(0, 0, 0));
        nombreLabel.setText("Nombre");

        nombreField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nombreField.setText("jTextField1");
        nombreField.setBorder(null);
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });

        descripcionLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        descripcionLabel.setForeground(new java.awt.Color(0, 0, 0));
        descripcionLabel.setText("Descrpcion");

        tipoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tipoLabel.setForeground(new java.awt.Color(0, 0, 0));
        tipoLabel.setText("Tipo");

        costoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        costoLabel.setForeground(new java.awt.Color(0, 0, 0));
        costoLabel.setText("Costo de producción");

        ventaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ventaLabel.setForeground(new java.awt.Color(0, 0, 0));
        ventaLabel.setText("Precio de venta");

        promocionLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        promocionLabel.setForeground(new java.awt.Color(0, 0, 0));
        promocionLabel.setText("Precio de promoción");

        tipoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tipoField.setText("jTextField1");
        tipoField.setBorder(null);
        tipoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoFieldActionPerformed(evt);
            }
        });

        costoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        costoField.setText("jTextField1");
        costoField.setBorder(null);
        costoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoFieldActionPerformed(evt);
            }
        });

        ventaField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ventaField.setText("jTextField1");
        ventaField.setBorder(null);
        ventaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaFieldActionPerformed(evt);
            }
        });

        promocionField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        promocionField.setText("jTextField1");
        promocionField.setBorder(null);
        promocionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promocionFieldActionPerformed(evt);
            }
        });

        descripcionTArea.setColumns(20);
        descripcionTArea.setRows(5);
        descripcionTArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descripcionTAreaKeyPressed(evt);
            }
        });
        descipcionSPane.setViewportView(descripcionTArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreLabel)
                            .addComponent(codigoLable)
                            .addComponent(descripcionLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nombreField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descipcionSPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(promocionLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ventaLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costoField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ventaField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(promocionField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 405, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(codigoLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descipcionSPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(costoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ventaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ventaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promocionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promocionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFieldActionPerformed
        codigoField.requestFocus();
    }//GEN-LAST:event_nombreFieldActionPerformed

    private void codigoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoFieldActionPerformed
        descripcionTArea.requestFocus();
    }//GEN-LAST:event_codigoFieldActionPerformed

    private void descripcionTAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionTAreaKeyPressed
        tipoField.requestFocus();
    }//GEN-LAST:event_descripcionTAreaKeyPressed

    private void tipoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoFieldActionPerformed
        costoField.requestFocus();
    }//GEN-LAST:event_tipoFieldActionPerformed

    private void costoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoFieldActionPerformed
        ventaField.requestFocus();
    }//GEN-LAST:event_costoFieldActionPerformed

    private void ventaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaFieldActionPerformed
        promocionField.requestFocus();
    }//GEN-LAST:event_ventaFieldActionPerformed

    private void promocionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promocionFieldActionPerformed
        cargaPlato();
    }//GEN-LAST:event_promocionFieldActionPerformed

    private void cargaPlato() {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoField;
    private javax.swing.JLabel codigoLable;
    private javax.swing.JTextField costoField;
    private javax.swing.JLabel costoLabel;
    private javax.swing.JScrollPane descipcionSPane;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JTextArea descripcionTArea;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField promocionField;
    private javax.swing.JLabel promocionLabel;
    private javax.swing.JTextField tipoField;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField ventaField;
    private javax.swing.JLabel ventaLabel;
    // End of variables declaration//GEN-END:variables
}
