/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tpmaquianasql.View.ingresar;

import com.mycompany.tpmaquianasql.Controler.PlatosData;
import com.mycompany.tpmaquianasql.Model.Platos;

import java.awt.Color;

/**
 *
 * @author ivanb
 */
public class PlatoPane extends javax.swing.JPanel {

    private Color defaultFontColor = new Color(190, 190, 190);
    private Color insertButtonFontColor = new Color(187, 187, 186);
    private Color insertButtonFontColorOnHover = new Color(255, 255, 255);

    private String[] predefinedText = { "Ingrese el codigo del plato", "Ingrese el nombre",
            "Ingrese una breve descripción", "Ingrese el tipo",
            "Ingrese el costo de producción", "Ingrese el precio de venta", "Ingrese el precio de promoción" };

    private PlatosData platosData;

    /**
     * Creates new form Plato
     */
    public PlatoPane(PlatosData platosData) {
        initComponents();

        this.platosData = platosData;

        successLabel.setVisible(false);

        setErrMsgs();
    }

    private void setErrMsgs() {
        codigoErrMsg.setVisible(false);
        nombreErrMsg.setVisible(false);
        tipoErrMsg.setVisible(false);
        descripcionErrMsg.setVisible(false);
        costoErrMsg.setVisible(false);
        ventaErrMsg.setVisible(false);
        promocionErrMsg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoLable = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        descripcionLabel = new javax.swing.JLabel();
        tipoLabel = new javax.swing.JLabel();
        costoLabel = new javax.swing.JLabel();
        ventaLabel = new javax.swing.JLabel();
        promocionLabel = new javax.swing.JLabel();
        tipoField = new javax.swing.JTextField();
        costoField = new javax.swing.JTextField();
        ventaField = new javax.swing.JTextField();
        promocionField = new javax.swing.JTextField();
        descripcionField = new javax.swing.JTextField();
        codigoErrMsg = new javax.swing.JLabel();
        nombreErrMsg = new javax.swing.JLabel();
        descripcionErrMsg = new javax.swing.JLabel();
        tipoErrMsg = new javax.swing.JLabel();
        costoErrMsg = new javax.swing.JLabel();
        ventaErrMsg = new javax.swing.JLabel();
        promocionErrMsg = new javax.swing.JLabel();
        insertButtonP = new javax.swing.JPanel();
        insertButtonL = new javax.swing.JLabel();
        successLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(650, 510));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codigoLable.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        codigoLable.setForeground(new java.awt.Color(0, 0, 0));
        codigoLable.setText("Código");
        add(codigoLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        codigoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        codigoField.setForeground(new java.awt.Color(190, 190, 190));
        codigoField.setText("Ingrese el codigo del plato");
        codigoField.setBorder(null);
        codigoField.setPreferredSize(new java.awt.Dimension(170, 19));
        codigoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoFieldFocusLost(evt);
            }
        });
        codigoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoFieldActionPerformed(evt);
            }
        });
        add(codigoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 380, -1));

        nombreLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(0, 0, 0));
        nombreLabel.setText("Nombre");
        add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        nombreField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nombreField.setForeground(new java.awt.Color(190, 190, 190));
        nombreField.setText("Ingrese el nombre");
        nombreField.setBorder(null);
        nombreField.setPreferredSize(new java.awt.Dimension(170, 19));
        nombreField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreFieldFocusLost(evt);
            }
        });
        nombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFieldActionPerformed(evt);
            }
        });
        add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 380, -1));

        descripcionLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        descripcionLabel.setForeground(new java.awt.Color(0, 0, 0));
        descripcionLabel.setText("Descrpcion");
        add(descripcionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        tipoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tipoLabel.setForeground(new java.awt.Color(0, 0, 0));
        tipoLabel.setText("Tipo");
        add(tipoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        costoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        costoLabel.setForeground(new java.awt.Color(0, 0, 0));
        costoLabel.setText("Costo de producción");
        add(costoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        ventaLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ventaLabel.setForeground(new java.awt.Color(0, 0, 0));
        ventaLabel.setText("Precio de venta");
        add(ventaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        promocionLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        promocionLabel.setForeground(new java.awt.Color(0, 0, 0));
        promocionLabel.setText("Precio de promoción");
        add(promocionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        tipoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tipoField.setForeground(new java.awt.Color(190, 190, 190));
        tipoField.setText("Ingrese el tipo");
        tipoField.setBorder(null);
        tipoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tipoFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tipoFieldFocusLost(evt);
            }
        });
        tipoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoFieldActionPerformed(evt);
            }
        });
        add(tipoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 380, -1));

        costoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        costoField.setForeground(new java.awt.Color(190, 190, 190));
        costoField.setText("Ingrese el costo de producción");
        costoField.setBorder(null);
        costoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                costoFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                costoFieldFocusLost(evt);
            }
        });
        costoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoFieldActionPerformed(evt);
            }
        });
        add(costoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 380, -1));

        ventaField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ventaField.setForeground(new java.awt.Color(190, 190, 190));
        ventaField.setText("Ingrese el precio de venta");
        ventaField.setBorder(null);
        ventaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ventaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ventaFieldFocusLost(evt);
            }
        });
        ventaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaFieldActionPerformed(evt);
            }
        });
        add(ventaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 380, -1));

        promocionField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        promocionField.setForeground(new java.awt.Color(190, 190, 190));
        promocionField.setText("Ingrese el precio de promoción");
        promocionField.setBorder(null);
        promocionField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                promocionFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                promocionFieldFocusLost(evt);
            }
        });
        promocionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promocionFieldActionPerformed(evt);
            }
        });
        add(promocionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 380, -1));

        descripcionField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        descripcionField.setForeground(new java.awt.Color(190, 190, 190));
        descripcionField.setText("Ingrese una breve descripción");
        descripcionField.setBorder(null);
        descripcionField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descripcionFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descripcionFieldFocusLost(evt);
            }
        });
        descripcionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionFieldActionPerformed(evt);
            }
        });
        add(descripcionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 380, -1));

        codigoErrMsg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        codigoErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        codigoErrMsg.setText("Mensaje de error");
        add(codigoErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 190, -1));

        nombreErrMsg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombreErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        nombreErrMsg.setText("Mensaje de error");
        add(nombreErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 190, -1));

        descripcionErrMsg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        descripcionErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        descripcionErrMsg.setText("Mensaje de error");
        add(descripcionErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 190, -1));

        tipoErrMsg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tipoErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        tipoErrMsg.setText("Mensaje de error");
        add(tipoErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 190, -1));

        costoErrMsg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        costoErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        costoErrMsg.setText("Mensaje de error");
        add(costoErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 190, -1));

        ventaErrMsg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ventaErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        ventaErrMsg.setText("Mensaje de error");
        add(ventaErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 190, -1));

        promocionErrMsg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        promocionErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        promocionErrMsg.setText("Mensaje de error");
        add(promocionErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 190, -1));

        insertButtonP.setBackground(new java.awt.Color(18, 33, 69));
        insertButtonP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertButtonP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        insertButtonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertButtonPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertButtonPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertButtonPMouseExited(evt);
            }
        });

        insertButtonL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        insertButtonL.setForeground(new java.awt.Color(187, 187, 186));
        insertButtonL.setText("Cargar");

        javax.swing.GroupLayout insertButtonPLayout = new javax.swing.GroupLayout(insertButtonP);
        insertButtonP.setLayout(insertButtonPLayout);
        insertButtonPLayout.setHorizontalGroup(
            insertButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertButtonPLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(insertButtonL)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        insertButtonPLayout.setVerticalGroup(
            insertButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertButtonPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertButtonL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(insertButtonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 90, -1));

        successLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        successLabel.setForeground(new java.awt.Color(0, 0, 0));
        successLabel.setText("El plato se ha cargado con éxito!");
        add(successLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 310, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonPMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_insertButtonPMouseClicked
        cargaPlato();
    }// GEN-LAST:event_insertButtonPMouseClicked

    private void insertButtonPMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_insertButtonPMouseEntered
        insertButtonL.setForeground(insertButtonFontColorOnHover);
    }// GEN-LAST:event_insertButtonPMouseEntered

    private void insertButtonPMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_insertButtonPMouseExited
        insertButtonL.setForeground(insertButtonFontColor);
    }// GEN-LAST:event_insertButtonPMouseExited

    private void nombreFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_nombreFieldFocusGained
        if (nombreField.getText().equals(predefinedText[1])) {
            nombreField.setText("");
        } else {
            nombreField.selectAll();
        }
        nombreField.setForeground(Color.BLACK);
    }// GEN-LAST:event_nombreFieldFocusGained

    private void descripcionFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_descripcionFieldFocusGained
        if (descripcionField.getText().equals(predefinedText[2])) {
            descripcionField.setText("");
        } else {
            descripcionField.selectAll();
        }
        descripcionField.setForeground(Color.BLACK);
    }// GEN-LAST:event_descripcionFieldFocusGained

    private void tipoFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_tipoFieldFocusGained
        if (tipoField.getText().equals(predefinedText[3])) {
            tipoField.setText("");
        } else {
            tipoField.selectAll();
        }
        tipoField.setForeground(Color.BLACK);
    }// GEN-LAST:event_tipoFieldFocusGained

    private void costoFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_costoFieldFocusGained
        if (costoField.getText().equals(predefinedText[4])) {
            costoField.setText("");
        } else {
            costoField.selectAll();
        }
        costoField.setForeground(Color.BLACK);
    }// GEN-LAST:event_costoFieldFocusGained

    private void ventaFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_ventaFieldFocusGained
        if (ventaField.getText().equals(predefinedText[5])) {
            ventaField.setText("");
        } else {
            ventaField.selectAll();
        }
        ventaField.setForeground(Color.BLACK);
    }// GEN-LAST:event_ventaFieldFocusGained

    private void promocionFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_promocionFieldFocusGained
        if (promocionField.getText().equals(predefinedText[6])) {
            promocionField.setText("");
        } else {
            promocionField.selectAll();
        }
        promocionField.setForeground(Color.BLACK);
    }// GEN-LAST:event_promocionFieldFocusGained

    private void codigoFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_codigoFieldFocusLost
        if (codigoField.getText().equals("")) {
            codigoField.setText(predefinedText[0]);
            codigoField.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_codigoFieldFocusLost

    private void nombreFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_nombreFieldFocusLost
        if (nombreField.getText().equals("")) {
            nombreField.setText(predefinedText[1]);
            nombreField.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_nombreFieldFocusLost

    private void descripcionFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_descripcionFieldFocusLost
        if (descripcionField.getText().equals("")) {
            descripcionField.setText(predefinedText[2]);
            descripcionField.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_descripcionFieldFocusLost

    private void tipoFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_tipoFieldFocusLost
        if (tipoField.getText().equals("")) {
            tipoField.setText(predefinedText[3]);
            tipoField.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_tipoFieldFocusLost

    private void costoFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_costoFieldFocusLost
        if (costoField.getText().equals("")) {
            costoField.setText(predefinedText[4]);
            costoField.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_costoFieldFocusLost

    private void ventaFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_ventaFieldFocusLost
        if (ventaField.getText().equals("")) {
            ventaField.setText(predefinedText[5]);
            ventaField.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_ventaFieldFocusLost

    private void promocionFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_promocionFieldFocusLost
        if (promocionField.getText().equals("")) {
            promocionField.setText(predefinedText[6]);
            promocionField.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_promocionFieldFocusLost

    private void nombreFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nombreFieldActionPerformed
        descripcionField.requestFocus();
    }// GEN-LAST:event_nombreFieldActionPerformed

    private void codigoFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_codigoFieldActionPerformed
        nombreField.requestFocus();
    }// GEN-LAST:event_codigoFieldActionPerformed

    private void tipoFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tipoFieldActionPerformed
        costoField.requestFocus();
    }// GEN-LAST:event_tipoFieldActionPerformed

    private void costoFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_costoFieldActionPerformed
        ventaField.requestFocus();
    }// GEN-LAST:event_costoFieldActionPerformed

    private void ventaFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ventaFieldActionPerformed
        promocionField.requestFocus();
    }// GEN-LAST:event_ventaFieldActionPerformed

    private void promocionFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_promocionFieldActionPerformed
        insertButtonP.requestFocus();
        cargaPlato();
    }// GEN-LAST:event_promocionFieldActionPerformed

    private void descripcionFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_descripcionFieldActionPerformed
        tipoField.requestFocus();
    }// GEN-LAST:event_descripcionFieldActionPerformed

    private void codigoFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_codigoFieldFocusGained
        if (codigoField.getText().equals(predefinedText[0])) {
            codigoField.setText("");
        } else {
            codigoField.selectAll();
        }
        codigoField.setForeground(Color.BLACK);
    }// GEN-LAST:event_codigoFieldFocusGained

    private void cargaPlato() {
        int P_Cod = 0, P_PrecioCosto = 0, P_PrecioVenta = 0, P_PrecioPromocion = 0;
        String P_Descripcion = descripcionField.getText(), P_Nombre = nombreField.getText(),
                P_Tipo = tipoField.getText(), temp;
        boolean correcto = true;

        successLabel.setVisible(false);

        if ((temp = codigoField.getText()).equals(predefinedText[0])) {
            codigoErrMsg.setText("Obligatorio");
            codigoErrMsg.setVisible(true);
            correcto = false;
        } else {
            try {
                P_Cod = Integer.parseInt(temp);
                codigoErrMsg.setVisible(false);
            } catch (NumberFormatException e) {
                codigoErrMsg.setText("Debe ser un entero");
                codigoErrMsg.setVisible(true);
                correcto = false;
            }
        }

        if (P_Nombre.equals(predefinedText[1])) {
            nombreErrMsg.setText("Obligatorio");
            nombreErrMsg.setVisible(true);
            correcto = false;
        } else if (P_Nombre.matches("\\D+")) {
            nombreErrMsg.setVisible(false);
        } else {
            nombreErrMsg.setText("No debe contener números");
            nombreErrMsg.setVisible(true);
            correcto = false;
        }

        if (P_Descripcion.equals(predefinedText[2])) {
            descripcionErrMsg.setText("Obligatorio");
            descripcionErrMsg.setVisible(true);
            correcto = false;
        } else {
            descripcionErrMsg.setVisible(false);
        }

        if (P_Tipo.equals(predefinedText[3])) {
            tipoErrMsg.setText("Obligatorio");
            tipoErrMsg.setVisible(true);
            correcto = false;
        } else if (P_Tipo.matches("\\D+")) {
            tipoErrMsg.setVisible(false);
        } else {
            tipoErrMsg.setText("No debe contener números");
            tipoErrMsg.setVisible(true);
            correcto = false;
        }

        if ((temp = costoField.getText()).equals(predefinedText[4])) {
            costoErrMsg.setText("Obligatorio");
            costoErrMsg.setVisible(true);
            correcto = false;
        } else {
            try {
                P_PrecioCosto = Integer.parseInt(temp);
                costoErrMsg.setVisible(false);
            } catch (NumberFormatException e) {
                costoErrMsg.setText("Debe ser un entero");
                costoErrMsg.setVisible(true);
                correcto = false;
            }
        }

        if ((temp = ventaField.getText()).equals(predefinedText[5])) {
            ventaErrMsg.setText("Obligatorio");
            ventaErrMsg.setVisible(true);
            correcto = false;
        } else {
            try {
                P_PrecioVenta = Integer.parseInt(temp);
                ventaErrMsg.setVisible(false);
            } catch (NumberFormatException e) {
                ventaErrMsg.setText("Debe ser un entero");
                ventaErrMsg.setVisible(true);
                correcto = false;
            }
        }

        if ((temp = promocionField.getText()).equals(predefinedText[6]) || temp.equals("")) {
            promocionErrMsg.setText("Obligatorio");
            promocionErrMsg.setVisible(true);
            correcto = false;
        } else {
            try {
                P_PrecioPromocion = Integer.parseInt(temp);
                promocionErrMsg.setVisible(false);
            } catch (NumberFormatException e) {
                promocionErrMsg.setText("Debe ser un entero");
                promocionErrMsg.setVisible(true);
                correcto = false;
            }
        }

        if (correcto) {
            Platos plato = new Platos(P_Cod, P_PrecioCosto, P_PrecioVenta, P_PrecioPromocion, P_Descripcion, P_Nombre,
                    P_Tipo);

            if (platosData.insertPlato(plato)) {
                successLabel.setVisible(true);

                //Reseteo de los campos de texto
                codigoField.setText(predefinedText[0]);
                nombreField.setText(predefinedText[1]);
                descripcionField.setText(predefinedText[2]);
                tipoField.setText(predefinedText[3]);
                costoField.setText(predefinedText[4]);
                ventaField.setText(predefinedText[5]);
                promocionField.setText(predefinedText[6]);

                codigoField.setForeground(defaultFontColor);
                nombreField.setForeground(defaultFontColor);
                descripcionField.setForeground(defaultFontColor);
                tipoField.setForeground(defaultFontColor);
                costoField.setForeground(defaultFontColor);
                ventaField.setForeground(defaultFontColor);
                promocionField.setForeground(defaultFontColor);
            }

            setErrMsgs();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoErrMsg;
    private javax.swing.JTextField codigoField;
    private javax.swing.JLabel codigoLable;
    private javax.swing.JLabel costoErrMsg;
    private javax.swing.JTextField costoField;
    private javax.swing.JLabel costoLabel;
    private javax.swing.JLabel descripcionErrMsg;
    private javax.swing.JTextField descripcionField;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JLabel insertButtonL;
    private javax.swing.JPanel insertButtonP;
    private javax.swing.JLabel nombreErrMsg;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel promocionErrMsg;
    private javax.swing.JTextField promocionField;
    private javax.swing.JLabel promocionLabel;
    private javax.swing.JLabel successLabel;
    private javax.swing.JLabel tipoErrMsg;
    private javax.swing.JTextField tipoField;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JLabel ventaErrMsg;
    private javax.swing.JTextField ventaField;
    private javax.swing.JLabel ventaLabel;
    // End of variables declaration//GEN-END:variables
}
