/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tpmaquianasql.View.Eliminar;

import com.mycompany.tpmaquianasql.Controler.MozosData;
import java.awt.Color;

/**
 *
 * @author ivanb
 */
public class MozoPane extends javax.swing.JPanel {

    private Color defaultFontColor = new Color(190, 190, 190);
    private Color deleteButtonFontColor = new Color(187, 187, 186);
    private Color deleteButtonFontColorOnHover = new Color(255, 255, 255);

    private static final String defaultText = "Ingrese el codigo del mozo que desea eliminar";

    private MozosData mozosData;

    /**
     * Creates new form MozoPane
     */
    public MozoPane(MozosData mozosData) {
        initComponents();

        this.mozosData = mozosData;

        codigoErrMsg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codigoErrMsg = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        codigoLable = new javax.swing.JLabel();
        deleteButtonP = new javax.swing.JPanel();
        deleteButtonL = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codigoErrMsg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        codigoErrMsg.setForeground(new java.awt.Color(255, 0, 0));
        codigoErrMsg.setText("Mensaje de error");
        jPanel1.add(codigoErrMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 190, -1));

        codigoField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        codigoField.setForeground(new java.awt.Color(190, 190, 190));
        codigoField.setText("Ingrese el codigo del mozo que desea eliminar");
        codigoField.setBorder(null);
        codigoField.setPreferredSize(new java.awt.Dimension(170, 19));
        codigoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codigoFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codigoFieldFocusLost(evt);
            }
        });
        codigoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoFieldActionPerformed(evt);
            }
        });
        jPanel1.add(codigoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 380, -1));

        codigoLable.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        codigoLable.setForeground(new java.awt.Color(0, 0, 0));
        codigoLable.setText("Código");
        jPanel1.add(codigoLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        deleteButtonP.setBackground(new java.awt.Color(18, 33, 69));
        deleteButtonP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButtonP.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        deleteButtonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButtonPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteButtonPMouseExited(evt);
            }
        });

        deleteButtonL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deleteButtonL.setForeground(new java.awt.Color(187, 187, 186));
        deleteButtonL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteButtonL.setText("Eliminar");

        javax.swing.GroupLayout deleteButtonPLayout = new javax.swing.GroupLayout(deleteButtonP);
        deleteButtonP.setLayout(deleteButtonPLayout);
        deleteButtonPLayout.setHorizontalGroup(
            deleteButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteButtonPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteButtonL, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        deleteButtonPLayout.setVerticalGroup(
            deleteButtonPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteButtonPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButtonL)
                .addContainerGap())
        );

        jPanel1.add(deleteButtonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void codigoFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_codigoFieldFocusGained
        if (codigoField.getText().equals(defaultText)) {
            codigoField.setText("");
        } else {
            codigoField.selectAll();
        }
        codigoField.setForeground(Color.BLACK);
    }// GEN-LAST:event_codigoFieldFocusGained

    private void codigoFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_codigoFieldFocusLost
        if (codigoField.getText().equals("")) {
            codigoField.setText(defaultText);
            codigoField.setForeground(defaultFontColor);
        }
    }// GEN-LAST:event_codigoFieldFocusLost

    private void codigoFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_codigoFieldActionPerformed
        deleteButtonP.requestFocus();
        eliminarMozo();
    }// GEN-LAST:event_codigoFieldActionPerformed

    private void deleteButtonPMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_deleteButtonPMouseClicked
        eliminarMozo();
    }// GEN-LAST:event_deleteButtonPMouseClicked

    private void deleteButtonPMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_deleteButtonPMouseEntered
        deleteButtonL.setForeground(deleteButtonFontColorOnHover);
    }// GEN-LAST:event_deleteButtonPMouseEntered

    private void deleteButtonPMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_deleteButtonPMouseExited
        deleteButtonL.setForeground(deleteButtonFontColor);
    }// GEN-LAST:event_deleteButtonPMouseExited

    private void eliminarMozo() {
        String temp;
        int codigo;

        if((temp = codigoField.getText()).equals(defaultText) || temp.equals("")) {
            codigoErrMsg.setText("Obligatorio");
            codigoErrMsg.setVisible(true);
        } else {
            try {
                codigoErrMsg.setVisible(false);
                codigo = Integer.parseInt(temp);

                mozosData.deleteMozo(codigo);
            } catch (NumberFormatException E) {
                codigoErrMsg.setText("Debe ser un entero");
                codigoErrMsg.setVisible(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codigoErrMsg;
    private javax.swing.JTextField codigoField;
    private javax.swing.JLabel codigoLable;
    private javax.swing.JLabel deleteButtonL;
    private javax.swing.JPanel deleteButtonP;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
